import { v4 as uuid } from "uuid";

/**
 * Product Database can be added here.
 * You can add products of your wish with different attributes
 * */

export const products = [
  {
    _id: uuid(),
    title: "Truck Art: Batman",
    images: [
      "https://res.cloudinary.com/dz0snqho8/image/upload/v1684437297/shippr/Shippr%20Images/looseTshirt/Truck_Art-1_lzn8zu.webp",
      "https://res.cloudinary.com/dz0snqho8/image/upload/v1684437298/shippr/Shippr%20Images/looseTshirt/Truck_Art-2_x3tiwe.webp",
    ],
    brand: "The Souled Store",
    price: 1499,
    discountpercent: 0.5,
    discountprice: 749,
    rating: 4.2,
    sizes: ["sm", "m", "l", "xl"],
    categoryName: "looseTshirt",
    instock: true,
    description: `This Truck Art: Batman t-shirt is a stylish and unique way to show your love for the Caped Crusader. The shirt features a bold and colorful design that is inspired by the traditional art of truck art. The design features a large image of Batman, along with his iconic bat symbol. The shirt is made from high-quality materials and is available in a variety of sizes. It is the perfect shirt for any Batman fan.`,
    stock: 10,
    inCart: false,
    inWishList: false,
  },

  {
    _id: uuid(),
    title: "TSS Originals: Out Of Office",
    images: [
      "https://res.cloudinary.com/dz0snqho8/image/upload/v1684437297/shippr/Shippr%20Images/looseTshirt/TSS_Originals-1_foj5dr.webp",
      "https://res.cloudinary.com/dz0snqho8/image/upload/v1684437297/shippr/Shippr%20Images/looseTshirt/TSS_Originals-2_e6y38d.webp",
    ],
    brand: "The Souled Store",
    price: 999,
    discountpercent: 0.25,
    discountprice: 749,
    rating: 3.9,
    sizes: ["sm", "m", "l", "xl"],
    categoryName: "looseTshirt",
    instock: true,
    description: `The TSS Originals: Out Of Office T-Shirt is the perfect way to let people know that you're not available. Made from 100% cotton, this comfortable and stylish t-shirt features the phrase "Out Of Office" in a bold, modern font. The shirt is available in a variety of colors and sizes, so you can find the perfect one to match your style. Whether you're taking a vacation, working from home, or just need a break from the office, the TSS Originals: Out Of Office T-Shirt is the perfect way to let people know that you're not available.`,
    stock: 50,
    inCart: false,
    inWishList: false,
  },

  {
    _id: uuid(),
    title: "Tom And Jerry: Thinking Tom",
    images: [
      "https://res.cloudinary.com/dz0snqho8/image/upload/v1684427707/shippr/Products/Tom_And_Jerry-1_uktpyt.webp",
      "https://res.cloudinary.com/dz0snqho8/image/upload/v1684427707/shippr/Products/Tom_And_Jerry-2_szdk2a.webp",
    ],
    brand: "The Souled Store",
    price: 499,
    discountpercent: 0.1,
    discountprice: 449,
    rating: 3.5,
    sizes: ["sm", "m", "l", "xl"],
    categoryName: "looseTshirt",
    instock: true,
    description: `The Tom And Jerry: Thinking Tom T-Shirt is a must-have for any fan of the classic cartoon duo. This comfortable and stylish t-shirt features a classic image of Tom sitting on a fence, deep in thought. The shirt is made from 100% cotton and is available in a variety of colors and sizes. Whether you're wearing it to the gym, running errands, or just lounging around the house, the Tom And Jerry: Thinking Tom T-Shirt is a great way to show your love for one of the most beloved cartoon characters of all time.`,
    stock: 50,
    inCart: false,
    inWishList: false,
  },

  {
    _id: uuid(),
    title: "Rick & Morty: Escape From Reality",
    images: [
      "https://res.cloudinary.com/dz0snqho8/image/upload/v1684437296/shippr/Shippr%20Images/looseTshirt/Rick_Morty-1_tghxd4.webp",
      "https://res.cloudinary.com/dz0snqho8/image/upload/v1684437297/shippr/Shippr%20Images/looseTshirt/Rick_Morty-2_izyxwb.webp",
    ],
    brand: "The Souled Store",
    price: 1499,
    discountpercent: 0.3,
    discountprice: 1049,
    rating: 4.4,
    sizes: ["sm", "m", "l", "xl"],
    categoryName: "looseTshirt",
    instock: true,
    description: ` The Rick & Morty: Escape From Reality T-Shirt is the perfect way to show your love for the hit Adult Swim show. This comfortable and stylish t-shirt features a design of Rick and Morty flying through space, with the words "Escape From Reality" written across the front. The shirt is made from 100% cotton and is available in a variety of colors and sizes. Whether you're wearing it to the gym, running errands, or just lounging around the house, the Rick & Morty: Escape From Reality T-Shirt is a great way to show your fandom for one of the funniest and most popular shows on TV.
    `,
    stock: 50,
    inCart: false,
    inWishList: false,
  },

  {
    _id: uuid(),
    title: "GOTG: Stay Weird",

    images: [
      "https://res.cloudinary.com/dz0snqho8/image/upload/v1684437296/shippr/Shippr%20Images/looseTshirt/GOTG-2_zs5ryj.webp",
      "https://res.cloudinary.com/dz0snqho8/image/upload/v1684437295/shippr/Shippr%20Images/looseTshirt/GOTG-1_xtc9xq.webp",
    ],
    brand: "The Souled Store",
    price: 599,
    discountpercent: 0.15,
    discountprice: 509,
    rating: 4.7,
    sizes: ["sm", "m", "l", "xl"],
    categoryName: "looseTshirt",
    instock: true,
    description: `The GOTG: Stay Weird T-Shirt is a must-have for any fan of the Guardians of the Galaxy. This comfortable and stylish t-shirt features the iconic quote "Stay Weird" from the film, along with a stylized image of the Guardians. The shirt is made from 100% cotton and is available in a variety of colors and sizes. Whether you're wearing it to the movies, running errands, or just lounging around the house, the GOTG: Stay Weird T-Shirt is a great way to show your love for one of the most popular superhero teams of all time.`,
    stock: 50,
    inCart: false,
    inWishList: false,
  },

  {
    _id: uuid(),
    title: "Truck Art: Iron Man",

    images: [
      "https://res.cloudinary.com/dz0snqho8/image/upload/v1684437295/shippr/Shippr%20Images/looseTshirt/Iron_Man-1_ydkqqp.webp",
      "https://res.cloudinary.com/dz0snqho8/image/upload/v1684437296/shippr/Shippr%20Images/looseTshirt/Iron_Man-2_gtihlu.webp",
    ],
    brand: "The Souled Store",
    price: 1999,
    discountpercent: 0.5,
    discountprice: 999,
    rating: 4.8,
    sizes: ["sm", "m", "l", "xl"],
    categoryName: "looseTshirt",
    instock: true,
    description: `The Truck Art: Iron Man T-Shirt is a unique and stylish way to show your love for the iconic Marvel superhero. This t-shirt features a vintage-inspired design of Iron Man's armor, rendered in the style of classic American truck art. The shirt is made from 100% cotton and is available in a variety of colors and sizes. Whether you're wearing it to the movies, running errands, or just lounging around the house, the Truck Art: Iron Man T-Shirt is a great way to show your fandom for one of the most popular superheroes of all time.`,
    stock: 50,
    inCart: false,
    inWishList: false,
  },

  {
    _id: uuid(),
    title: "Deadpool: Chimichangas!",
    images: [
      "https://res.cloudinary.com/dz0snqho8/image/upload/v1684437295/shippr/Shippr%20Images/looseTshirt/Deadpool-1_pytskz.webp",
      "https://res.cloudinary.com/dz0snqho8/image/upload/v1684437296/shippr/Shippr%20Images/looseTshirt/Deadpool-2_smfnip.webp",
    ],
    brand: "The Souled Store",
    price: 1299,
    discountpercent: 0.2,
    discountprice: 1039,
    rating: 3.9,
    sizes: ["sm", "m", "l", "xl"],
    categoryName: "looseTshirt",
    instock: true,
    description: `The Deadpool: Chimichangas! T-Shirt is the perfect way to show your love for the Merc with a Mouth. This comfortable and stylish t-shirt features a large, bold image of Deadpool holding a chimichanga, with the words "Chimichangas!" written across the front. The shirt is made from 100% cotton and is available in a variety of colors and sizes. Whether you're wearing it to the movies, running errands, or just lounging around the house, the Deadpool: Chimichangas! T-Shirt is a great way to show your fandom for one of the most popular superheroes of all time.`,
    stock: 50,
    inCart: false,
    inWishList: false,
  },

  {
    _id: uuid(),
    title: "The Lion King: Tribal Pattern",
    images: [
      "https://res.cloudinary.com/dz0snqho8/image/upload/v1684437302/shippr/Shippr%20Images/Shirts/Tribal_Pattern-1_jicfcu.webp",
      "https://res.cloudinary.com/dz0snqho8/image/upload/v1684437300/shippr/Shippr%20Images/Shirts/Tribal_Pattern-2_oealc1.webp",
    ],
    brand: "The Souled Store",
    price: 2499,
    discountpercent: 0.3,
    discountprice: 1749,
    rating: 4.5,
    sizes: ["sm", "m", "l", "xl"],
    categoryName: "shirt",
    instock: true,
    description: `The The Lion King: Tribal Pattern shirt is a stylish and comfortable way to show your love for the classic Disney film. This shirt features a vibrant tribal pattern inspired by the Pride Lands, with the iconic The Lion King logo prominently displayed on the front. The shirt is made from 100% cotton and is available in a variety of colors and sizes. Whether you're wearing it to a movie night, a casual day out, or just lounging around the house, the The Lion King: Tribal Pattern shirt is a great way to show your love for one of the most beloved Disney films of all time.`,
    stock: 50,
    inCart: false,
    inWishList: false,
  },

  {
    _id: uuid(),
    title: "Star Wars: Storm Trooper Pattern",
    images: [
      "https://res.cloudinary.com/dz0snqho8/image/upload/v1684437300/shippr/Shippr%20Images/Shirts/Storm_Trooper_Pattern-1_tglduz.webp",
      "https://res.cloudinary.com/dz0snqho8/image/upload/v1684437300/shippr/Shippr%20Images/Shirts/Storm_Trooper_Pattern-2_fffdjp.webp",
    ],
    brand: "The Souled Store",
    price: 1799,
    discountpercent: 0.4,
    discountprice: 1079,
    rating: 4.2,
    sizes: ["sm", "m", "l", "xl"],
    categoryName: "shirt",
    instock: true,
    description: `The Star Wars: Stormtrooper Pattern shirt is a stylish and comfortable way to show your love for the iconic Star Wars franchise. This shirt features a classic stormtrooper pattern on a black background, and is made from 100% cotton. The shirt is available in a variety of sizes, so you can find the perfect fit for you. Whether you're going to a Star Wars convention, watching a movie, or just running errands, the Star Wars: Stormtrooper Pattern shirt is a great way to show your fandom.`,
    stock: 50,
    inCart: false,
    inWishList: false,
  },

  {
    _id: uuid(),
    title: "Oxford Shirt",

    images: [
      "https://res.cloudinary.com/dz0snqho8/image/upload/v1684437299/shippr/Shippr%20Images/Shirts/Oxford_Shirt-1_txmuez.webp",
      "https://res.cloudinary.com/dz0snqho8/image/upload/v1684437299/shippr/Shippr%20Images/Shirts/Oxford_Shirt-2_ymrcek.webp",
    ],
    brand: "The Souled Store",
    price: 899,
    discountpercent: 0.05,
    discountprice: 855,
    rating: 3.2,
    sizes: ["sm", "m", "l", "xl"],
    categoryName: "shirt",
    instock: true,
    description: `This pink Oxford shirt is a classic and versatile piece that can be dressed up or down. It is made from 100% cotton and has a button-down collar, long sleeves, and a straight hem. The shirt is available in a variety of sizes and fits slim through the body. The pink color is a bold and eye-catching choice that is perfect for adding a pop of color to any outfit. The shirt can be dressed up with a blazer and tie for a formal event or dressed down with jeans and sneakers for a casual look.`,
    stock: 50,
    inCart: false,
    inWishList: false,
  },

  {
    _id: uuid(),
    title: "Garfield: Made To Lounge",
    images: [
      "https://res.cloudinary.com/dz0snqho8/image/upload/v1684437299/shippr/Shippr%20Images/Shirts/Made_To_Lounge-1_eg8wzi.webp",
      "https://res.cloudinary.com/dz0snqho8/image/upload/v1684437299/shippr/Shippr%20Images/Shirts/Made_To_Lounge-2_ghaquh.webp",
    ],
    brand: "The Souled Store",
    price: 1499,
    discountpercent: 0,
    discountprice: 1499,
    rating: 4.7,
    sizes: ["sm", "m", "l", "xl"],
    categoryName: "shirt",
    instock: true,
    description: `The Garfield: Made To Lounge shirt is the perfect way to show your love for the world's most famous lasagna-loving cat. This comfortable and stylish shirt features a large print of Garfield lounging on a couch, with the words "Made To Lounge" written across the front. The shirt is made from 100% cotton and is available in a variety of colors and sizes. Whether you're wearing it to the movies, running errands, or just lounging around the house, the Garfield: Made To Lounge shirt is a great way to show your fandom for one of the most beloved comic strip characters of all time.`,
    stock: 50,
    inCart: false,
    inWishList: false,
  },

  {
    _id: uuid(),
    title: "Archie: Comic Strip",
    images: [
      "https://res.cloudinary.com/dz0snqho8/image/upload/v1684437298/shippr/Shippr%20Images/Shirts/Comic_Strip-1_cwsnhh.webp",
      "https://res.cloudinary.com/dz0snqho8/image/upload/v1684437299/shippr/Shippr%20Images/Shirts/Comic_Strip-2_uqdqwu.webp",
    ],
    brand: "The Souled Store",
    price: 1699,
    discountpercent: 0.25,
    discountprice: 1275,
    rating: 4.3,
    sizes: ["sm", "m", "l", "xl"],
    categoryName: "shirt",
    instock: true,
    description: `The Archie: Comic Strip shirt is a must-have for any fan of the classic Archie comics. This comfortable and stylish t-shirt features a classic image of Archie, Betty, Veronica, and Jughead, along with the words "Archie Comics" written across the front. The shirt is made from 100% cotton and is available in a variety of colors and sizes. Whether you're wearing it to the comic book store, running errands, or just lounging around the house, the Archie: Comic Strip shirt is a great way to show your love for one of the most beloved comic book characters of all time.`,
    stock: 50,
    inCart: false,
    inWishList: false,
  },

  {
    _id: uuid(),
    title: "Harry Potter: Gryffindor",
    images: [
      "https://res.cloudinary.com/dz0snqho8/image/upload/v1684437299/shippr/Shippr%20Images/Shirts/Gryffindor-1_gmlhhe.webp",
      "https://res.cloudinary.com/dz0snqho8/image/upload/v1684437299/shippr/Shippr%20Images/Shirts/Gryffindor-2_cobxav.webp",
    ],
    brand: "The Souled Store",
    price: 2599,
    discountpercent: 0.6,
    discountprice: 1040,
    rating: 3.9,
    sizes: ["sm", "m", "l", "xl"],
    categoryName: "shirt",
    instock: true,
    description: `The Harry Potter: Gryffindor shirt is a must-have for any fan of the Wizarding World. This comfortable and stylish t-shirt features the iconic Gryffindor lion crest, along with the words "Gryffindor" and "Where dwell the brave at heart." The shirt is made from 100% cotton and is available in a variety of colors and sizes. Whether you're wearing it to the movies, running errands, or just lounging around the house, the Harry Potter: Gryffindor shirt is a great way to show your love for one of the most popular book and film series of all time.`,
    stock: 50,
    inCart: false,
    inWishList: false,
  },

  {
    _id: uuid(),
    title: "Plaid: Blue Pink and White",
    images: [
      "https://res.cloudinary.com/dz0snqho8/image/upload/v1684437298/shippr/Shippr%20Images/Shirts/Blue_and_White-1_lzl3il.webp",
      "https://res.cloudinary.com/dz0snqho8/image/upload/v1684437298/shippr/Shippr%20Images/Shirts/Blue_and_White-2_pqucyz.webp",
    ],
    brand: "The Souled Store",
    price: 1999,
    discountpercent: 0,
    discountprice: 1999,
    rating: 4,
    sizes: ["sm", "m", "l", "xl"],
    categoryName: "shirt",
    instock: true,
    description: `This plaid shirt is a classic and versatile piece that can be dressed up or down. The blue, pink, and white plaid pattern is both stylish and eye-catching, and the shirt is made from a soft and comfortable cotton fabric. The shirt has a button-down front and a relaxed fit, making it perfect for everyday wear. Whether you're running errands, going out with friends, or just lounging around the house, this plaid shirt is a great option.`,
    stock: 50,
    inCart: false,
    inWishList: false,
  },

  {
    _id: uuid(),
    title: "Marvel: Avengers 63",
    images: [
      "https://res.cloudinary.com/dz0snqho8/image/upload/v1684437298/shippr/Shippr%20Images/Shirts/Avengers_63-1_qwk70c.webp",
      "https://res.cloudinary.com/dz0snqho8/image/upload/v1684437297/shippr/Shippr%20Images/Shirts/Avengers_63-2_ocas0b.webp",
    ],
    brand: "The Souled Store",
    price: 2999,
    discountpercent: 0.4,
    discountprice: 1800,
    rating: 4.6,
    sizes: ["sm", "m", "l", "xl"],
    categoryName: "shirt",
    instock: true,
    description: `The Marvel: Avengers 63 shirt is a must-have for any fan of the Avengers. This comfortable and stylish t-shirt features the iconic cover art from Avengers #63, which features the team's first battle against the Kree. The shirt is made from 100% cotton and is available in a variety of colors and sizes. Whether you're wearing it to the movies, running errands, or just lounging around the house, the Marvel: Avengers 63 shirt is a great way to show your love for one of the most popular superhero teams of all time.`,
    stock: 50,
    inCart: false,
    inWishList: false,
  },

  {
    _id: uuid(),
    title: "TSS Originals: Beach Vibes",
    images: [
      "https://res.cloudinary.com/dz0snqho8/image/upload/v1684437298/shippr/Shippr%20Images/Shirts/Beach_Vibes-1_c7qfwj.webp",
      "https://res.cloudinary.com/dz0snqho8/image/upload/v1684437298/shippr/Shippr%20Images/Shirts/Beach_Vibes-2_xbibkv.webp",
    ],
    brand: "The Souled Store",
    price: 899,
    discountpercent: 0.1,
    discountprice: 810,
    rating: 3.6,
    sizes: ["sm", "m", "l", "xl"],
    categoryName: "shirt",
    instock: true,
    description: `The TSS Originals: Beach Vibes T-Shirt is the perfect way to show your love for the beach. This comfortable and stylish t-shirt features a colorful design of palm trees, waves, and a sun with sunglasses. The shirt is made from 100% cotton and is available in a variety of colors and sizes. Whether you're wearing it to the beach, running errands, or just lounging around the house, the TSS Originals: Beach Vibes T-Shirt is a great way to show your love for one of the most relaxing places on Earth.`,
    stock: 50,
    inCart: false,
    inWishList: false,
  },

  {
    _id: uuid(),
    title: "The Office: Characters",
    images: [
      "https://res.cloudinary.com/dz0snqho8/image/upload/v1684437302/shippr/Shippr%20Images/Tshirts/The_Office-1_vsttlt.webp",
      "https://res.cloudinary.com/dz0snqho8/image/upload/v1684437302/shippr/Shippr%20Images/Tshirts/The_Office-2_kybe8v.webp",
    ],
    brand: "The Souled Store",
    price: 599,
    discountpercent: 0.2,
    discountprice: 480,
    rating: 4.6,
    sizes: ["sm", "m", "l", "xl"],
    categoryName: "tshirt",
    instock: true,
    description: `The The Office: Characters T-Shirt is a must-have for any fan of the beloved comedy series. This comfortable and stylish t-shirt features a collage of the show's most iconic characters, including Michael Scott, Jim Halpert, Pam Beesly, Dwight Schrute, and more. The shirt is made from 100% cotton and is available in a variety of colors and sizes. Whether you're wearing it to a party, a barbecue, or just lounging around the house, the The Office: Characters T-Shirt is a great way to show your love for one of the funniest and most popular shows of all time.`,
    stock: 50,
    inCart: false,
    inWishList: false,
  },

  {
    _id: uuid(),
    title: "The Phantom: Necessary",
    images: [
      "https://res.cloudinary.com/dz0snqho8/image/upload/v1684437302/shippr/Shippr%20Images/Tshirts/ThePhantom-1_xngj9f.webp",
      "https://res.cloudinary.com/dz0snqho8/image/upload/v1684437302/shippr/Shippr%20Images/Tshirts/ThePhantom-2_nteyej.webp",
    ],
    brand: "The Souled Store",
    price: 399,
    discountpercent: 0.2,
    discountprice: 319,
    rating: 2.8,
    sizes: ["sm", "m", "l", "xl"],
    categoryName: "tshirt",
    instock: true,
    description: `The Phantom: Necessary T-Shirt is a must-have for any fan of the iconic pulp hero. This comfortable and stylish t-shirt features a classic image of the Phantom, along with the words "The Phantom: Necessary." The shirt is made from 100% cotton and is available in a variety of colors and sizes. Whether you're wearing it to the comic book store, running errands, or just lounging around the house, the The Phantom: Necessary T-Shirt is a great way to show your love for one of the most beloved comic book characters of all time.`,
    stock: 50,
    inCart: false,
    inWishList: false,
  },

  {
    _id: uuid(),
    title: "Supima: Smoke Grey",
    images: [
      "https://res.cloudinary.com/dz0snqho8/image/upload/v1684437301/shippr/Shippr%20Images/Tshirts/Supima-1_taa4ca.webp",
      "https://res.cloudinary.com/dz0snqho8/image/upload/v1684437302/shippr/Shippr%20Images/Tshirts/Supima-2_yk1bav.webp",
    ],
    brand: "The Souled Store",
    price: 1499,
    discountpercent: 0.25,
    discountprice: 1125,
    rating: 3.7,
    sizes: ["sm", "m", "l", "xl"],
    categoryName: "tshirt",
    instock: true,
    description: `The Supima: Smoke Grey T-Shirt is a classic and versatile piece that can be dressed up or down. Made from 100% Supima cotton, this shirt is soft, comfortable, and durable. The smoke grey color is flattering on all skin tones and goes with everything. Whether you're wearing it to the office, out on the town, or just lounging around the house, the Supima: Smoke Grey T-Shirt is a great choice.`,
    stock: 50,
    inCart: false,
    inWishList: false,
  },

  {
    _id: uuid(),
    title: "Solids: White",
    images: [
      "https://res.cloudinary.com/dz0snqho8/image/upload/v1684437301/shippr/Shippr%20Images/Tshirts/Solids-white-1_t5xdia.webp",
      "https://res.cloudinary.com/dz0snqho8/image/upload/v1684437301/shippr/Shippr%20Images/Tshirts/Solids-white-2_k8zjtf.webp",
    ],
    brand: "The Souled Store",
    price: 499,
    discountpercent: 0,
    discountprice: 499,
    rating: 3.5,
    sizes: ["sm", "m", "l", "xl"],
    categoryName: "tshirt",
    instock: true,
    description: `The Solids: White T-Shirt is a classic and versatile piece that can be dressed up or down. Made from 100% cotton, this comfortable and stylish t-shirt is perfect for any occasion. The soft fabric and relaxed fit make it a great choice for lounging around the house or running errands. The white color is timeless and goes with everything, so you can wear it with any outfit. Whether you're dressing up for a night out or just staying casual, the Solids: White T-Shirt is a must-have for any wardrobe.`,
    stock: 50,
    inCart: false,
    inWishList: false,
  },

  {
    _id: uuid(),
    title: "Looney Tunes: Bugs Bunny",
    images: [
      "https://res.cloudinary.com/dz0snqho8/image/upload/v1684437301/shippr/Shippr%20Images/Tshirts/Looney_Tunes-1_wakeyb.webp",
      "https://res.cloudinary.com/dz0snqho8/image/upload/v1684437300/shippr/Shippr%20Images/Tshirts/Looney_Tunes-2_jyzrxo.webp",
    ],
    brand: "The Souled Store",
    price: 799,
    discountpercent: 0.35,
    discountprice: 520,
    rating: 3.8,
    sizes: ["sm", "m", "l", "xl"],
    categoryName: "tshirt",
    instock: true,
    description: `The Looney Tunes: Bugs Bunny T-Shirt is a must-have for any fan of the iconic cartoon character. This comfortable and stylish t-shirt features a classic image of Bugs Bunny, wearing his signature red bow tie and carrot. The shirt is made from 100% cotton and is available in a variety of colors and sizes. Whether you're wearing it to the park, running errands, or just lounging around the house, the Looney Tunes: Bugs Bunny T-Shirt is a great way to show your love for one of the most beloved cartoon characters of all time.`,
    stock: 50,
    inCart: false,
    inWishList: false,
  },

  {
    _id: uuid(),
    title: "Solids: Foam Green",
    images: [
      "https://res.cloudinary.com/dz0snqho8/image/upload/v1684437300/shippr/Shippr%20Images/Tshirts/FoamGreen-1_ldgmoy.webp",
      "https://res.cloudinary.com/dz0snqho8/image/upload/v1684437300/shippr/Shippr%20Images/Tshirts/FoamGreen-2_b40xqm.webp",
    ],
    brand: "The Souled Store",
    price: 1399,
    discountpercent: 0.5,
    discountprice: 700,
    rating: 3.3,
    sizes: ["sm", "m", "l", "xl"],
    categoryName: "tshirt",
    instock: true,
    description: `The Solids: Foam Green T-Shirt is a simple yet stylish t-shirt that is perfect for any occasion. Made from 100% cotton, this comfortable and soft t-shirt features a solid foam green color. The shirt is available in a variety of sizes, so you can find the perfect fit for you. Whether you're wearing it to the gym, running errands, or just lounging around the house, the Solids: Foam Green T-Shirt is a great way to add a touch of style to your everyday look.`,
    stock: 50,
    inCart: false,
    inWishList: false,
  },

  {
    _id: uuid(),
    title: "Popeye: Fight Time",
    images: [
      "https://res.cloudinary.com/dz0snqho8/image/upload/v1684437300/shippr/Shippr%20Images/Tshirts/Popeye-1_ffhcif.webp",
      "https://res.cloudinary.com/dz0snqho8/image/upload/v1684437301/shippr/Shippr%20Images/Tshirts/Popeye-2_augftb.webp",
    ],
    brand: "The Souled Store",
    price: 1199,
    discountpercent: 0.25,
    discountprice: 899,
    rating: 4,
    categoryName: "tshirt",
    instock: true,
    description: `The Popeye: Fight Time T-Shirt is a must-have for any fan of the iconic sailor man. This comfortable and stylish t-shirt features a classic image of Popeye flexing his muscles, with the words "Fight Time" written across the front. The shirt is made from 100% cotton and is available in a variety of colors and sizes. Whether you're wearing it to the gym, running errands, or just lounging around the house, the Popeye: Fight Time T-Shirt is a great way to show your love for one of the most beloved cartoon characters of all time.`,
    stock: 50,
    inCart: false,
    inWishList: false,
  },
];
