import { v4 as uuid } from "uuid";

export const ToastType = {
  Warn: "warn",
  Success: "success",
  Info: "info",
  Error: "error",
};

export const ActionType = {
  InitialDataFetch: "INITIAL_DATA_FETCH",
  ToggleNav: "TOGGLE_NAV",
  ChangeFilter: "CHANGE_FILTER",
  ClearFilter: "CLEAR_FILTER",
  SetWishList: "SET_WISHLIST",
  SetCartList: "SET_CARTLIST",
  SetCartPriceDetails: "SET_CART_PRICE_DETAILS",
  ResetCartPriceDetails: "RESET_CART_PRICE_DETAILS",
  ClearCart: "CLEAR_CART",
  AddAddress: "ADD_ADDRESS",
  EditAddress: "EDIT_ADDRESS",
  DeleteAddress: "DELETE_ADDRESS",
  ADD_ORDER: "ADD_ORDER",
  Updated_checkoutAddress: "UPDATE_CHECKOUT_ADDRESS",
};

export const Filters = {
  SortBy: "sortBy",
  Categories: "categories",
  Rating: "rating",
  Sizes: "sizes",
  PriceRange: "priceRange",
  Search: "search",
};

export const CartListActionType = {
  Increment: "increment",
  Decrement: "decrement",
};

export const Categories = {
  tshirt: "T-shirt",
  shirt: "Shirt",
  looseTshirt: "Loose_T-shirt",
};

export const Sizes = {
  s: "S",
  m: "M",
  l: "L",
  xl: "XL",
  xxl: "XXL",
};
export const SortBy = {
  LowToHigh: "Low-to-High",
  HighToLow: "High-to-Low",
};

export const stateLists = [
  "Andhra Pradesh",
  "Arunachal Pradesh",
  "Assam",
  "Bihar",
  "Chhattisgarh",
  "Delhi",
  "Goa",
  "Gujarat",
  "Haryana",
  "Himachal Pradesh",
  "Jharkhand",
  "Karnataka",
  "Kerala",
  "Madhya Pradesh",
  "Maharashtra",
  "Manipur",
  "Meghalaya",
  "Mizoram",
  "Nagaland",
  "Odisha",
  "Punjab",
  "Rajasthan",
  "Sikkim",
  "Tamil Nadu",
  "Telangana",
  "Tripura",
  "Uttar Pradesh",
  "Uttarakhand",
  "West Bengal",
];

export const RandomAddressList = [
  {
    id: uuid(),
    name: "Rajesh Kumar",
    address: "201, Royal Apartments, Vijayanagar",
    mobile: "9876543210",
    city: "Bangalore",
    state: "Karnataka",
    country: "India",
    pincode: "560040",
  },
  {
    id: uuid(),
    name: "Sneha Sharma",
    address: "304, Tulsi Nagar",
    mobile: "9765432109",
    city: "Varanasi",
    state: "Uttar Pradesh",
    country: "India",
    pincode: "221001",
  },
  {
    id: uuid(),
    name: "Amit Patel",
    address: "15, Shanti Vihar Colony",
    mobile: "9654321098",
    city: "Jaipur",
    state: "Rajasthan",
    country: "India",
    pincode: "302001",
  },
  {
    id: uuid(),
    name: "Priya Singhania",
    address: "501, Green View Towers, Park Street",
    mobile: "9543210987",
    city: "Kolkata",
    state: "West Bengal",
    country: "India",
    pincode: "700053",
  },
  {
    id: uuid(),
    name: "Anand Verma",
    address: "10, Silver Heights, Vastrapur",
    mobile: "9432109876",
    city: "Ahmedabad",
    state: "Gujarat",
    country: "India",
    pincode: "380015",
  },
  {
    id: uuid(),
    name: "Deepika Khanna",
    address: "401, Sai Enclave, MG Road",
    mobile: "9321098765",
    city: "Gurugram",
    state: "Haryana",
    country: "India",
    pincode: "122001",
  },
  {
    id: uuid(),
    name: "Rahul Desai",
    address: "102, Rosewood Colony, Vikhroli",
    mobile: "9210987654",
    city: "Mumbai",
    state: "Maharashtra",
    country: "India",
    pincode: "400083",
  },
  {
    id: uuid(),
    name: "Neha Reddy",
    address: "204, Sapphire Heights, Gachibowli",
    mobile: "9109876543",
    city: "Hyderabad",
    state: "Telangana",
    country: "India",
    pincode: "500032",
  },
  {
    id: uuid(),
    name: "Vikram Mehra",
    address: "701, Pearl Residency, Navrangpura",
    mobile: "9098765432",
    city: "Ahmedabad",
    state: "Gujarat",
    country: "India",
    pincode: "380009",
  },
  {
    id: uuid(),
    name: "Anjali Kapoor",
    address: "502, Diamond Park, Rajpur Road",
    mobile: "9876543210",
    city: "Dehradun",
    state: "Uttarakhand",
    country: "India",
    pincode: "248001",
  },
];
